### ISSUE TITLE
Todo 순서 변경 기능 구현

### ISSUE THREAD

**Issue by ferrariRoma** [extreme-todo/backend#61]

**Comment by ferrariRoma** [comment]
# 기본적인 로직 브레인스토밍 with 희정님
- [ ] 전체 todo 불러올 때는 index데코레이터를 붙인 column를 기준으로 order by asc으로 조회한다.

- [ ] todo 추가할 때 order 값 설정하기 _확정: 좋은 아이디어 있으면 수정 가능_
1. db에서 done column이 false인 데이터를 불러온다.
2. 해당 데이터의 length를 측정한다. 혹은 전체 todo를 order by desc 해서 가장 상단의 data의 order value를 참조해도 된다.
3. 그 length에 1을 더한다.
4. 그 값을 새로운 todo의 order value로 사용한다.

- [ ] done을 했을 때 _확정: 좋은 아이디어 있으면 수정 가능_
- [ ] delete 할 때 _확정: 좋은 아이디어 있으면 수정 가능_
1. 해당 todo의 order value보다 높은 order value를 가진 todo를 가지고 온다.
2. todo의 order를 1씩 뺀다.
3. 해당 todo의 order value는 null로 update 한다.

- [ ] 순서를 변경할 때 _미정: 작업 전 한 번 더 이야기 해서 확정하기_
1. 해당 todo의 변경된 order value보다 같거나 높은 order value를 가진 todo를 가지고 온다.
2. todo의 order를 1씩 더한다.

위 방법은 순서를 위로 끌어 올렸을 때만 가능한 로직이다. 아래로 내렸을 때는 작동되지 않는다.

1. todo 다 가지고 온다.
2. 변경된 순서에 맞게 order를 다시 다 재입력한다.
4. save한다.
