### ISSUE TITLE
Todo Order 이슈 수정

### ISSUE THREAD

**Issue by imhjnoh** [extreme-todo/backend#70]
~~- [ ] addTodo시 날짜와 관계없이 맨 마지막 order를 부여하는 이슈 수정~~

- [x] front에서 order를 추가하는 방법 다시금 검증하기

- [x] order 처리하는 거 수정하기
- [x] indexed 초기화 해두고, 하나하나 설정하고 done 보내보면서 제대로 사라지는지 확인해보기
- [x] postman으로 추가하면서 검증해보기
- [x] plusOne 테스트 코드 작성하기
- [x] addTodo 테스트 코드 검증 및 수정하기
